### ISSUE TITLE
Compatibility with Journey into the Light mod

### ISSUE THREAD

**Issue by danmvision** [DenisMasterHerobrine/TheAfterdark#15]
Hi, 

there's an issue happening when you have The afterdark mod installed with Journey into the Light mod.

A member of JITL community helped me through this. 
Here's the issue:

The error is happening inside the afterdark code, it replaces some functionalities of vanilla's  FireBlock
and when jitl is creating the dimension (which have a lot of fire) it fails.

He said he has the solution and will post it here.

Thanks

**Comment by samjviana** [comment]
Here’s the exact error that occurs (from his `latest.log`):

<details><summary><code>latest.log</code></summary>

```log
[08Nov2024 08:33:39.977] [Server thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Chunk source main thread executor for jitl:boil
net.minecraft.ReportedException: Feature placement
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap.lambda$applyStep$19(ChunkMap.java:641) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:559) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:568) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.managedBlock(ServerChunkCache.java:533) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:159) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.getChunk(Level.java:202) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.LevelReader.getChunk(LevelReader.java:130) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.getChunk(Level.java:196) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.getChunk(ServerLevel.java:2951) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.BulkSectionAccess.lambda$getSection$0(BulkSectionAccess.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.12/it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:454) ~[fastutil-8.5.12.jar%23155!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.BulkSectionAccess.getSection(BulkSectionAccess.java:32) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.BulkSectionAccess.getBlockState(BulkSectionAccess.java:44) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/jitl@2.2.1/net.jitl.common.block.portal.logic.JPortal.findExistingPortal(JPortal.java:199) ~[JITL-1.21.1-2.2.1.jar%23617!/:?]
	at TRANSFORMER/jitl@2.2.1/net.jitl.common.block.portal.logic.JPortal.getOrCreatePortalLocation(JPortal.java:76) ~[JITL-1.21.1-2.2.1.jar%23617!/:?]
	at TRANSFORMER/jitl@2.2.1/net.jitl.common.block.portal.logic.JPortal.getTransitionForLevel(JPortal.java:59) ~[JITL-1.21.1-2.2.1.jar%23617!/:?]
	at TRANSFORMER/jitl@2.2.1/net.jitl.common.block.portal.JBasePortalBlock.getPortalDestination(JBasePortalBlock.java:254) ~[JITL-1.21.1-2.2.1.jar%23617!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.PortalProcessor.getPortalDestination(PortalProcessor.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.handlePortal(Entity.java:2183) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.baseTick(Entity.java:442) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:396) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.tick(Entity.java:425) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2392) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.player.Player.tick(Player.java:281) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:556) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:260) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.tick(Connection.java:412) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:159) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1051) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.server.level.WorldGenRegion cannot be cast to class net.minecraft.world.level.Level (net.minecraft.server.level.WorldGenRegion and net.minecraft.world.level.Level are in module minecraft@1.21.1 of loader 'TRANSFORMER' @4df7b4ac)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.FireBlock.handler$cbj000$the_afterdark$preventGrassBurning(FireBlock.java:1585) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.FireBlock.isValidFireLocation(FireBlock.java) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.FireBlock.canSurvive(FireBlock.java:154) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.canSurvive(BlockBehaviour.java:793) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.SimpleBlockFeature.place(SimpleBlockFeature.java:23) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.Feature.place(Feature.java:168) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.ConfiguredFeature.place(ConfiguredFeature.java:28) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.lambda$placeWithContext$4(PlacedFeature.java:54) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.placeWithContext(PlacedFeature.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.place(PlacedFeature.java:38) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.RandomPatchFeature.place(RandomPatchFeature.java:28) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.Feature.place(Feature.java:168) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.ConfiguredFeature.place(ConfiguredFeature.java:28) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.lambda$placeWithContext$4(PlacedFeature.java:54) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.placeWithContext(PlacedFeature.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.placement.PlacedFeature.placeWithBiomeCheck(PlacedFeature.java:42) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:396) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStatusTasks.generateFeatures(ChunkStatusTasks.java:154) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.apply(ChunkStep.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap.applyStep(ChunkMap.java:628) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.GenerationChunkHolder.applyStep(GenerationChunkHolder.java:64) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkGenerationTask.scheduleChunkInLayer(ChunkGenerationTask.java:143) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkGenerationTask.scheduleLayer(ChunkGenerationTask.java:121) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkGenerationTask.scheduleNextLayer(ChunkGenerationTask.java:74) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkGenerationTask.runUntilWait(ChunkGenerationTask.java:59) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap.lambda$runGenerationTask$21(ChunkMap.java:657) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.21.1-20240808.144430-srg.jar%23474!/:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```
</details>

This can be fixed by ensuring that `dev.denismasterherobrine.afterdark.mixin.MixinFireBlock:preventGrassBurning()` checks the type of `BlockView world` before casting it to `World`, like this:

```java
if (world instanceof World) {
    FireCheck.GrassAroundCheck((World) world, pos, cir);
}
```

**Comment by danmvision** [comment]
Thanks for the fix !!
